name: My Custom Windows Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    env:
      RENDEZVOUS_SERVER: tdisupport.ddns.net:21116
      RELAY_SERVER: tdisupport.ddns.net:21117
      RS_PUB_KEY: Db+kfSNgJQlup2RHwYBlw0NGBG88P27vPI7V9pFLYxFA=
      VCPKG_ROOT: C:\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows-static

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0"

      - name: Setup vcpkg + opus
        shell: pwsh
        run: |
          if (Test-Path "C:\vcpkg") { Remove-Item -Recurse -Force "C:\vcpkg" }
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          if (Test-Path "vcpkg.json") { Rename-Item vcpkg.json vcpkg.json.bak }
          if (Test-Path "vcpkg-configuration.json") { Rename-Item vcpkg-configuration.json vcpkg-configuration.json.bak }
          C:\vcpkg\vcpkg.exe install opus libvpx libyuv libaom --triplet x64-windows-static
          dir C:\vcpkg\installed\x64-windows-static\include\vpx
          if (Test-Path "vcpkg.json.bak") { Rename-Item vcpkg.json.bak vcpkg.json }
          if (Test-Path "vcpkg-configuration.json.bak") { Rename-Item vcpkg-configuration.json.bak vcpkg-configuration.json }

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Windows
        shell: bash
        run: |
          export VCPKG_ROOT="C:/vcpkg"
          python3 build.py --flutter

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Roger-Support-Windows
          path: flutter/build/windows/x64/runner/Release/
